---
pipeline: JUMP_ORF_ORF_Batch2
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: true
  well_column: Metadata_Well
  external :
    perform: true
    file: orf_metadata.tsv
    merge_column: broad_sample
normalize:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
normalize_negcon:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
feature_select:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
feature_select_negcon:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: true
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2021_05_31_Batch2
plates:
  - name: BR00121556
    process: true
  - name: BR00121555
    process: true
  - name: BR00121554
    process: true
  - name: BR00121553
    process: true
  - name: BR00121552
    process: true
  - name: BR00121551
    process: true
  - name: BR00121550
    process: true
  - name: BR00121549
    process: true
  - name: BR00121548
    process: true
  - name: BR00121547
    process: true
  - name: BR00121546
    process: true
  - name: BR00121545
    process: true
  - name: BR00121544
    process: true
  - name: BR00121543
    process: true
  - name: BR00123525
    process: true
  - name: BR00123528B
    process: true
  - name: BR00123529
    process: true
  - name: BR00123530
    process: true
  - name: BR00123526
    process: true
  - name: BR00123527
    process: true
process: true