---
pipeline: JUMP_ORF_ORF_Batch10
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: true
  well_column: Metadata_Well
  external :
    perform: true
    file: orf_metadata.tsv
    merge_column: broad_sample
normalize:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
normalize_negcon:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
feature_select:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
feature_select_negcon:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: true
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2021_08_02_Batch10
plates:
  - name: BR00126399
    process: true
  - name: BR00126398
    process: true
  - name: BR00126397
    process: true
  - name: BR00126396
    process: true
  - name: BR00126395
    process: true
  - name: BR00126394
    process: true
  - name: BR00126393
    process: true
  - name: BR00126392
    process: true
  - name: BR00126391
    process: true
  - name: BR00126390
    process: true
  - name: BR00126389
    process: true
  - name: BR00126388
    process: true
  - name: BR00126387
    process: true
  - name: BR00126386
    process: true
  - name: BR00126385
    process: true
  - name: BR00126403
    process: true
  - name: BR00126402
    process: true
  - name: BR00126401
    process: true
  - name: BR00126400
    process: true
  - name: BR00124794
    process: true
process: true