---
pipeline: Feature select all batches
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: false
  well_column: Metadata_Well
  external :
    perform: false
    file:
    merge_column:
normalize:
  perform: false
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
feature_select:
  perform: true
  features: infer
  level: all
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: false
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2021_04_26_Batch1
plates:
  - name: BR00121540
    process: true
  - name: BR00121541
    process: true
process: true
---
batch: 2021_05_31_Batch2
plates:
  - name: BR00123531
    process: true
process: true
---
batch: 2021_05_10_Batch3
plates:
  - name: BR00123630
    process: true
process: true
---
batch: 2021_05_17_Batch4
plates:
  - name: BR00123522
    process: true
process: true
---
batch: 2021_06_07_Batch5
plates:
  - name: BR00123946
    process: true
process: true
---
batch: 2021_06_14_Batch6
plates:
  - name: BR00124774
    process: true
process: true
---
batch: 2021_06_21_Batch7
plates:
  - name: BR00125180
    process: true
process: true
---
batch: 2021_07_12_Batch8
plates:
  - name: BR00125637
    process: true
process: true
---
batch: 2021_07_26_Batch9
plates:
  - name: BR00126061
    process: true
process: true
---
batch: 2021_08_02_Batch10
plates:
  - name: BR00124793
    process: true
process: true
---
batch: 2021_08_09_Batch11
plates:
  - name: BR00126544
    process: true
process: true
---
batch: 2021_08_23_Batch12
plates:
  - name: BR00126707
    process: true
process: true
---
batch: 2021_08_30_Batch13
plates:
  - name: BR00123538
    process: true
process: true
