---
pipeline: JUMP_ORF_ORF_Batch4
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: true
  well_column: Metadata_Well
  external :
    perform: true
    file: orf_metadata.tsv
    merge_column: broad_sample
normalize:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
normalize_negcon:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
feature_select:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
feature_select_negcon:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: true
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2021_05_17_Batch4
plates:
  - name: BR00123787
    process: true
  - name: BR00123786
    process: true
  - name: BR00123785
    process: true
  - name: BR00123791
    process: true
  - name: BR00123790
    process: true
  - name: BR00123509
    process: true
  - name: BR00123510
    process: true
  - name: BR00123511
    process: true
  - name: BR00123789
    process: true
  - name: BR00123788
    process: true
  - name: BR00123512
    process: true
  - name: BR00123513
    process: true
  - name: BR00123514
    process: true
  - name: BR00123515
    process: true
  - name: BR00123516
    process: true
  - name: BR00123517
    process: true
  - name: BR00123518
    process: true
  - name: BR00123519
    process: true
  - name: BR00123520
    process: true
  - name: BR00123521
    process: true
process: true