---
pipeline: JUMP_ORF_ORF_Batch11
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: true
  well_column: Metadata_Well
  external :
    perform: true
    file: orf_metadata.tsv
    merge_column: broad_sample
normalize:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
normalize_negcon:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
feature_select:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
feature_select_negcon:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: true
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2021_08_09_Batch11
plates:
  - name: BR00126542
    process: true
  - name: BR00126541
    process: true
  - name: BR00126540
    process: true
  - name: BR00126539
    process: true
  - name: BR00126538
    process: true
  - name: BR00126537
    process: true
  - name: BR00126536
    process: true
  - name: BR00126535
    process: true
  - name: BR00126534
    process: true
  - name: BR00126521
    process: true
  - name: BR00126520
    process: true
  - name: BR00126553
    process: true
  - name: BR00126552
    process: true
  - name: BR00126551
    process: true
  - name: BR00126550
    process: true
  - name: BR00126549
    process: true
  - name: BR00126548
    process: true
  - name: BR00126547
    process: true
  - name: BR00126546
    process: true
  - name: BR00126545
    process: true
process: true