---
pipeline: JUMP_ORF_ORF_Batch9
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: true
  well_column: Metadata_Well
  external :
    perform: true
    file: orf_metadata.tsv
    merge_column: broad_sample
normalize:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
normalize_negcon:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
feature_select:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
feature_select_negcon:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: true
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2021_07_26_Batch9
plates:
  - name: BR00126060
    process: true
  - name: BR00126057
    process: true
  - name: BR00126058
    process: true
  - name: BR00126059
    process: true
  - name: BR00126056
    process: true
  - name: BR00126055
    process: true
  - name: BR00126054
    process: true
  - name: BR00126053
    process: true
  - name: BR00126052
    process: true
  - name: BR00126051
    process: true
  - name: BR00126045
    process: true
  - name: BR00126044
    process: true
  - name: BR00126043
    process: true
  - name: BR00124791
    process: true
  - name: BR00124790
    process: true
  - name: BR00126050
    process: true
  - name: BR00126049
    process: true
  - name: BR00126048
    process: true
  - name: BR00126047
    process: true
  - name: BR00126046
    process: true
process: true