---
pipeline: JUMP_ORF_Target2
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: true
  well_column: Metadata_Well
  external :
    perform: true
    file: JUMP-Target-2_compound_metadata.tsv
    merge_column: broad_sample
normalize:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
normalize_negcon:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
feature_select:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
feature_select_negcon:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: true
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2021_04_26_Batch1
plates:
  - name: BR00121438
    process: true
  - name: BR00121439
    process: true
process: true
---
batch: 2021_05_31_Batch2
plates:
  - name: BR00121437
    process: true
process: true
---
batch: 2021_05_10_Batch3
plates:
  - name: BR00121436
    process: true
process: true
---
batch: 2021_05_17_Batch4
plates:
  - name: BR00121425
    process: true
process: true
---
batch: 2021_06_07_Batch5
plates:
  - name: BR00121430
    process: true
process: true
---
batch: 2021_06_14_Batch6
plates:
  - name: BR00121429
    process: true
process: true
---
batch: 2021_06_21_Batch7
plates:
  - name: BR00121424
    process: true
process: true
---
batch: 2021_07_12_Batch8
plates:
  - name: BR00121428
    process: true
process: true
---
batch: 2021_07_26_Batch9
plates:
  - name: BR00121427
    process: true
process: true
---
batch: 2021_08_02_Batch10
plates:
  - name: BR00121423
    process: true
process: true
---
batch: 2021_08_09_Batch11
plates:
  - name: BR00121426
    process: true
process: true
---
batch: 2021_08_23_Batch12
plates:
  - name: BR00126113
    process: true
  - name: BR00126114
    process: true
  - name: BR00126115
    process: true
  - name: BR00126116
    process: true
  - name: BR00126117
    process: true
process: true
---
batch: 2021_08_30_Batch13
plates:
  - name: BR00127149
    process: true
  - name: BR00127147
    process: true
  - name: BR00127148
    process: true
  - name: BR00127145
    process: true
  - name: BR00127146
    process: true
process: true