---
pipeline: JUMP_ORF_ORF_Batch7
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: true
  well_column: Metadata_Well
  external :
    perform: true
    file: orf_metadata.tsv
    merge_column: broad_sample
normalize:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
normalize_negcon:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
feature_select:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
feature_select_negcon:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: true
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2021_06_21_Batch7
plates:
  - name: BR00125164
    process: true
  - name: BR00125163
    process: true
  - name: BR00125162
    process: true
  - name: BR00124785
    process: true
  - name: BR00124784
    process: true
  - name: BR00125169
    process: true
  - name: BR00125168
    process: true
  - name: BR00125167
    process: true
  - name: BR00125166
    process: true
  - name: BR00125165
    process: true
  - name: BR00125174
    process: true
  - name: BR00125173
    process: true
  - name: BR00125172
    process: true
  - name: BR00125171
    process: true
  - name: BR00125170
    process: true
  - name: BR00125179
    process: true
  - name: BR00125178
    process: true
  - name: BR00125177
    process: true
  - name: BR00125176
    process: true
  - name: BR00125175
    process: true
process: true