---
pipeline: JUMP_ORF_ORF_Batch1
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: true
  well_column: Metadata_Well
  external :
    perform: true
    file: orf_metadata.tsv
    merge_column: broad_sample
normalize:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
normalize_negcon:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
feature_select:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
feature_select_negcon:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: true
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2021_04_26_Batch1
plates:
  - name: BR00121539
    process: true
  - name: BR00121537
    process: true
  - name: BR00121538
    process: true
  - name: BR00121557
    process: true
  - name: BR00121561
    process: true
  - name: BR00121564
    process: true
  - name: BR00121566
    process: true
  - name: BR00121565
    process: true
  - name: BR00121563
    process: true
  - name: BR00121562
    process: true
  - name: BR00121558
    process: true
  - name: BR00121559
    process: true
  - name: BR00121560
    process: true
  - name: BR00117035
    process: true
  - name: BR00117036
    process: true
  - name: BR00117041
    process: true
  - name: BR00117040
    process: true
  - name: BR00117039
    process: true
  - name: BR00117038
    process: true
  - name: BR00117037
    process: true
process: true