---
pipeline: JUMP_ORF_ORF_Batch6
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: true
  well_column: Metadata_Well
  external :
    perform: true
    file: orf_metadata.tsv
    merge_column: broad_sample
normalize:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
normalize_negcon:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
feature_select:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
feature_select_negcon:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: true
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2021_06_14_Batch6
plates:
  - name: BR00124766
    process: true
  - name: BR00124767
    process: true
  - name: BR00124768
    process: true
  - name: BR00124769
    process: true
  - name: BR00123945
    process: true
  - name: BR00124761
    process: true
  - name: BR00124770
    process: true
  - name: BR00124776
    process: true
  - name: BR00124777
    process: true
  - name: BR00124775
    process: true
  - name: BR00124778
    process: true
  - name: BR00124779
    process: true
  - name: BR00124771
    process: true
  - name: BR00124772
    process: true
  - name: BR00124773
    process: true
process: true