---
pipeline: JUMP_ORF_ORF_Batch8
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: true
  well_column: Metadata_Well
  external :
    perform: true
    file: orf_metadata.tsv
    merge_column: broad_sample
normalize:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
normalize_negcon:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
feature_select:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
feature_select_negcon:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: true
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2021_07_12_Batch8
plates:
  - name: BR00125621
    process: true
  - name: BR00125620
    process: true
  - name: BR00125619
    process: true
  - name: BR00124788
    process: true
  - name: BR00124787
    process: true
  - name: BR00125626
    process: true
  - name: BR00125625
    process: true
  - name: BR00125624
    process: true
  - name: BR00125623
    process: true
  - name: BR00125622
    process: true
  - name: BR00125631
    process: true
  - name: BR00125630
    process: true
  - name: BR00125629
    process: true
  - name: BR00125628
    process: true
  - name: BR00125627
    process: true
  - name: BR00125636
    process: true
  - name: BR00125635
    process: true
  - name: BR00125634
    process: true
  - name: BR00125633
    process: true
process: true